# -*- coding: utf-8 -*-
"""desafio01-minicurso-katie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AtN7t-tJ0E4DQ5NgkuG8bOvgZoWwKI45
"""

def pedido(pedido1, pedido2, desconto):
  total = 0
  for i in comida:
    i = i.lower()
    if i == 'lasanha':
      total += 8.00
      print('A lasanha custa R$8.00')
    elif i == 'estrogonofe':
      total += 11.00
      print('O estrogonofe custa R$ 11.00')
    else:
      print('No momento temos apenas lasanha e estrogonofe para servir')
  for i in bebida:
    i = i.lower()
    if i == 'refrigerante':
      total += 3.00
      print('O refrigerante custa R$3.00')
    elif i == 'suco':
      total += 2.50
      print('O suco custa R$2.50')
    else:
      print(f'No momento temos refrigerante e água para servir.')
  print(f'Total do seu pedido é de R${total:.2f}')
  if desconto == 'sim':
    novo_total = total - (10 * (total) / 100)
    print(f'Para pagamento a vista estamos com 10% de desconto, novo total é de R$ {novo_total}')
  if total >= 20.00:
    print('Você vai ganhar um brinde, um bombom!')

pedido1 =  input('Qual seu pedido comida? ')
pedido2 = input('E para beber? ')
desconto = ('O pagamento é em dinheiro? ')
comida = []
bebida = []
comida.append(pedido1)
bebida.append(pedido2)
pedido(pedido1, pedido2, desconto)

"""# Nova seção"""